"use client";
import { ResponsiveContainer, ComposedChart, Area, Line, XAxis, YAxis, CartesianGrid, Tooltip, Legend, BarChart, Bar } from "recharts";
import type { OutlookSlot } from "@/lib/consumer-fixture";
import type { scheduleSeries, HistoryEntry } from "@/lib/consumer-metrics";
import { slotTime } from "@/lib/consumer";

type SeriesRow = { time: string; [key: string]: string | number };
type ChartSeries = { key: string; name: string; color: string };
function ChartDataTable({ data, series, unit, caption = `${unit} · forecast and meter data` }: { data: SeriesRow[]; series: ChartSeries[]; unit: string; caption?: string }) {
  return <details className="evidence-readings"><summary>View chart data</summary><div className="evidence-scroll" role="region" aria-label="Chart data" tabIndex={0}><table><caption>{caption}</caption><thead><tr><th scope="col">Time (IST)</th>{series.map(s => <th scope="col" key={s.key}>{s.name} ({unit})</th>)}</tr></thead><tbody>{data.map((row, i) => <tr key={i}><td>{row.time}</td>{series.map(s => <td key={s.key}>{row[s.key]}</td>)}</tr>)}</tbody></table></div></details>;
}
function Plot({ data, series, unit, bar = false, context = `${unit} · times in IST · forecast and meter data` }: { data: SeriesRow[]; series: ChartSeries[]; unit: string; bar?: boolean; context?: string }) {
  const maxValue = Math.max(1, ...data.flatMap(row => series.map(s => Number(row[s.key]) || 0))); const yMax = Math.max(4, Math.ceil((maxValue + Math.max(1, maxValue * 0.08)) / 4) * 4);
  const children = <><CartesianGrid vertical={false} stroke="var(--line)" strokeDasharray="2 5" /><XAxis dataKey="time" interval={7} minTickGap={32} axisLine={false} tickLine={false} tick={{ fill: "var(--muted)", fontSize: 10 }} /><YAxis width={30} domain={[0, yMax]} tickFormatter={value => String(value)} axisLine={false} tickLine={false} tick={{ fill: "var(--muted)", fontSize: 10 }} /><Tooltip cursor={{ stroke: "var(--line)", strokeWidth: 1 }} labelFormatter={label => `${label} IST`} formatter={(value, name) => [`${Number(value).toFixed(1)} ${unit}`, name]} contentStyle={{ background: "var(--surface)", borderColor: "var(--line)", borderRadius: 12, boxShadow: "0 8px 20px rgba(20, 42, 39, .12)" }} /><Legend verticalAlign="top" align="right" wrapperStyle={{ fontSize: 11, paddingBottom: 8 }} /></>;
  const lineSeries = [...series].sort((a, b) => (a.key === "renewableKW" ? -1 : b.key === "renewableKW" ? 1 : a.key === "windKW" ? 1 : b.key === "windKW" ? -1 : 0));
  return <><p className="chart-unit">{context}</p><div className="consumer-chart"><ResponsiveContainer width="100%" height="100%">{bar ? <BarChart data={data} margin={{ top: 8, right: 8, bottom: 0, left: -12 }}>{children}{series.map(s => <Bar key={s.key} dataKey={s.key} name={s.name} fill={s.color} isAnimationActive={false} radius={[3, 3, 0, 0]} />)}</BarChart> : <ComposedChart data={data} margin={{ top: 8, right: 8, bottom: 0, left: -12 }}>{children}{series.map(s => <Area key={`area-${s.key}`} type="monotone" dataKey={s.key} fill={s.color} fillOpacity={0.07} stroke="none" legendType="none" isAnimationActive={false} />)}{lineSeries.map(s => <Line key={s.key} type="monotone" dataKey={s.key} name={s.name} stroke={s.color} dot={false} activeDot={{ r: 4, strokeWidth: 2 }} strokeWidth={s.key === "renewableKW" ? 3.2 : 2.8} strokeLinecap="round" strokeLinejoin="round" isAnimationActive={false} />)}</ComposedChart>}</ResponsiveContainer></div><ChartDataTable data={data} series={series} unit={unit} caption={context} /></>;
}
export function RenewableOutlook({ slots, source }: { slots: OutlookSlot[]; source?: string }) {
  const peak = slots.reduce((best, slot) => slot.renewableKW > best.renewableKW ? slot : best, slots[0]); const peakStart = peak ? Math.max(0, peak.slot - 2) : 0; const peakEnd = peak ? Math.min(48, peak.slot + 3) : 0;
  return <article className="schedule-card"><h2>Renewable outlook</h2><p>{source ?? "Solar and wind availability for the selected day."} Values are estimates, not guaranteed supply or a live grid commitment.</p>{slots.length ? <><div className="outlook-callout"><span className="status-pill absorb">BEST ESTIMATED WINDOW</span><strong>{slotTime(peakStart)}–{slotTime(peakEnd)} IST</strong><small>{peak.renewableKW.toFixed(1)} kW peak combined availability</small></div><Plot data={slots.map(s => ({ ...s, time: slotTime(s.slot) }))} unit="kW" context="kW · estimated availability · 30-minute slots" series={[{ key: "solarKW", name: "Solar", color: "var(--amber)" }, { key: "windKW", name: "Wind", color: "var(--blue)" }, { key: "renewableKW", name: "Combined", color: "var(--green)" }]} /></> : <p>Forecast is unavailable. Retry when the forecast provider is connected.</p>}</article>;
}
export function ScheduleChart({ rows }: { rows: ReturnType<typeof scheduleSeries> }) {
  return <article className="schedule-card"><h2>Your load schedule</h2><p>Usual versus accepted power across the day. An unaccepted offer adds no committed load.</p>{rows.length ? <Plot data={rows} unit="kW" series={[{ key: "baseline", name: "Usual", color: "var(--muted)" }, { key: "accepted", name: "Accepted", color: "var(--blue)" }]} /> : <p>Accept an offer to see its schedule.</p>}</article>;
}
export function VerificationHistoryChart({ history }: { history: HistoryEntry[] }) {
  const rows = history.slice().reverse().map((entry, index) => ({ time: String(index + 1), recorded: Number(entry.recorded_kwh), eligible: Number(entry.eligible_kwh) }));
  return <article className="schedule-card"><h2>Verification history</h2><p>Each bar identifies a verification record below. Shifted energy is not energy saved.</p>{rows.length ? <Plot data={rows} unit="kWh" bar series={[{ key: "recorded", name: "Recorded", color: "var(--blue)" }, { key: "eligible", name: "Eligible shift", color: "var(--violet)" }]} /> : <p>No verifications yet.</p>}</article>;
}
