"use client";

import { BatteryCharging, ChevronLeft, Clock3, Droplets, Factory, LoaderCircle, Plus, ShieldCheck } from "lucide-react";
import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { activityTypes, type Activity, type ActivityType } from "@/lib/activities";

const presets = [{ type: activityTypes[0], description: "Charge before you leave", icon: BatteryCharging, tone: "amber", name: "My EV", duration: "2" }, { type: activityTypes[1], description: "Heat before you need it", icon: Droplets, tone: "blue", name: "Evening hot water", duration: "1" }, { type: activityTypes[2], description: "Move an approved process", icon: Factory, tone: "violet", name: "Production process", duration: "2" }] as const;
export default function ActivitiesPage() {
 const [selected,setSelected]=useState<ActivityType>(activityTypes[0]); const [name,setName]=useState("My EV"); const [earliest,setEarliest]=useState("13:00"); const [deadline,setDeadline]=useState("17:00"); const [duration,setDuration]=useState("2"); const [interruptible,setInterruptible]=useState(true); const [activities,setActivities]=useState<Activity[]>([]); const [message,setMessage]=useState(""); const [busy,setBusy]=useState(false);
 useEffect(()=>{ fetch("/api/activities").then(async r=>{const body=await r.json(); if(r.ok)setActivities(body.activities ?? []);}).catch(()=>setMessage("Unable to load saved activities.")); },[]);
 function choose(type:ActivityType){const p=presets.find(x=>x.type===type)!; setSelected(type);setName(p.name);setDuration(p.duration);setMessage("");}
 async function addActivity(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setMessage(""); try {const response=await fetch("/api/activities",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({type:selected,name,earliestStart:earliest,latestFinish:deadline,durationHours:duration,interruptible})}); const body=await response.json(); if(!response.ok)throw new Error(body.error||"Unable to save activity."); setActivities(items=>[body.activity,...items]);setMessage("Activity saved to your account.");}catch(e){setMessage(e instanceof Error?e.message:"Unable to save activity.");}finally{setBusy(false);}}
 return <main className="app-shell"><section className="hero-panel activity-hero"><Link className="back-link" href="/consumer/today"><ChevronLeft size={17}/> Today</Link><div className="hero-copy"><p className="kicker">YOUR FLEXIBLE LOADS</p><h1>What needs to get done?</h1><p className="hero-description">Tell us the deadline. We’ll find a renewable-aligned time that fits your routine.</p></div></section><section className="content-section"><div className="section-heading"><div><span className="section-label">QUICK SETUP</span><h2>Choose an activity</h2></div><Plus size={22} color="var(--amber)"/></div><div className="preset-grid">{presets.map(({type,description,icon:Icon,tone})=><button type="button" key={type} className={`preset-card ${selected===type?"selected":""}`} onClick={()=>choose(type)}><span className={`activity-icon ${tone}`}><Icon size={20}/></span><strong>{type}</strong><small>{description}</small></button>)}</div><form className="activity-form" onSubmit={addActivity}><label>Activity name<input required maxLength={80} value={name} onChange={e=>setName(e.target.value)}/></label><div className="form-row"><label>Can start at<input required type="time" step="1800" value={earliest} onChange={e=>setEarliest(e.target.value)}/></label><label>Need it by<input required type="time" step="1800" value={deadline} onChange={e=>setDeadline(e.target.value)}/></label></div><label>Usually takes (hours)<input required type="number" min="0.5" max="12" step="0.5" value={duration} onChange={e=>setDuration(e.target.value)}/></label><label className="toggle-row"><span><strong>Can pause if needed?</strong><small>Useful for scheduling around changing renewable availability.</small></span><input type="checkbox" checked={interruptible} onChange={e=>setInterruptible(e.target.checked)}/></label><button className="primary-button form-submit" disabled={busy}>{busy&&<LoaderCircle size={16} className="spin"/>}{busy?"Saving…":"Save activity"} <Plus size={16}/></button></form>{message&&<p className="form-message" role="status">{message}</p>}<div className="activity-safety"><ShieldCheck size={17}/><span>Your activities are saved privately to your signed-in account.</span></div>{activities.length>0&&<div className="saved-activities"><span className="section-label">SAVED ACTIVITIES</span>{activities.map(a=><article className="saved-activity" key={a.id}><div className="activity-icon amber"><Clock3 size={18}/></div><div><strong>{a.name}</strong><small>{a.type} · {a.earliest_start ?? a.earliestStart}–{a.latest_finish ?? a.latestFinish} · {(a.duration_minutes ?? a.durationHours * 60)/60}h{a.interruptible?" · pauseable":" · continuous"}</small></div></article>)}</div>}</section></main>;
}


