"use client";

import { useMemo, useState } from "react";
import { Bar, BarChart, CartesianGrid, ComposedChart, Legend, Line, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import type { BatteryDispatch, Scenario, ScheduleEntry } from "@/domain/types";
import { rankGridRecommendations } from "@/domain/grid-recommendations";

const slotLabel = (index: number) => `${String(Math.floor(index / 2)).padStart(2, "0")}:${index % 2 ? "30" : "00"}`;
const demandAt = (scenario: Scenario, slot: number, entries: ScheduleEntry[]) => scenario.forecast[slot].fixedDemandKW + entries.filter((entry) => slot >= entry.startSlot && slot < entry.endSlot).reduce((sum, entry) => sum + entry.powerKW, 0);

export function OperatorAnalytics({ scenario, schedules, battery }: { scenario: Scenario; schedules: ScheduleEntry[]; battery: BatteryDispatch[] }) {
  const [selectedSlot, setSelectedSlot] = useState(26);
  const baseline = useMemo(() => scenario.activities.map((activity) => ({ activityId: activity.id, startSlot: activity.baselineStart, endSlot: activity.baselineStart + activity.durationSlots, powerKW: activityPower(activity), accepted: true, version: 0, data_source: "simulation" as const })), [scenario.activities]);
  const data = scenario.forecast.map((slot) => ({ time: slotLabel(slot.index), renewable: Number(slot.renewableKW.toFixed(1)), baseline: Number(demandAt(scenario, slot.index, baseline).toFixed(1)), scheduled: Number(demandAt(scenario, slot.index, schedules).toFixed(1)) }));
  const renewable = scenario.forecast.map((slot) => ({ time: slotLabel(slot.index), solar: Number(slot.solarKW.toFixed(1)), wind: Number(slot.windKW.toFixed(1)), combined: Number(slot.renewableKW.toFixed(1)) }));
  const batteryRows = battery.map((point) => ({ time: slotLabel(point.slot), soc: point.stateOfChargeKWh, action: point.action }));
  const recommendations = useMemo(() => rankGridRecommendations(scenario, selectedSlot), [scenario, selectedSlot]);
  const selected = scenario.forecast[selectedSlot];
  const selectedDemand = selected ? demandAt(scenario, selectedSlot, schedules) : 0;
  const selectedOverload = selectedDemand > scenario.sitePowerLimitKW;
  return <div className="operator-analytics">
    <div className="analytics-grid">
      <section className="card analytics-card analytics-wide"><div className="analytics-heading"><div><div className="label">System view · 48 half-hour slots</div><h2>Renewable supply against demand</h2></div><span className="source">{scenario.data_source === "simulation" ? "Simulation" : scenario.data_source}</span></div><div className="analytics-chart"><ResponsiveContainer width="100%" height="100%"><ComposedChart data={data} margin={{ top: 10, right: 10, left: -18, bottom: 4 }}><CartesianGrid stroke="var(--line)" strokeDasharray="3 3" /><XAxis dataKey="time" minTickGap={34} tick={{ fill: "var(--muted)", fontSize: 10 }} /><YAxis unit=" kW" tick={{ fill: "var(--muted)", fontSize: 10 }} /><Tooltip contentStyle={{ background: "var(--surface-2)", border: "1px solid var(--line)", borderRadius: 10 }} /><Legend wrapperStyle={{ fontSize: 11 }} /><Line dataKey="renewable" name="Renewable" stroke="var(--amber)" strokeWidth={2.5} dot={false} /><Line dataKey="scheduled" name="Scheduled demand" stroke="var(--blue)" strokeWidth={2} dot={false} /><Line dataKey="baseline" name="Baseline demand" stroke="var(--muted)" strokeDasharray="5 4" dot={false} /></ComposedChart></ResponsiveContainer></div><p className="chart-note">Amber supply above demand marks room to absorb renewable power; demand above supply marks a protect condition. Values are {scenario.data_source === "simulation" ? "simulated" : "estimated"} kW.</p></section>
      <section className="card analytics-card"><div className="label">Generation mix</div><h2>Where renewable power comes from</h2><div className="analytics-chart compact"><ResponsiveContainer width="100%" height="100%"><BarChart data={renewable} margin={{ top: 8, right: 4, left: -18, bottom: 4 }}><CartesianGrid stroke="var(--line)" strokeDasharray="3 3" /><XAxis dataKey="time" minTickGap={30} tick={{ fill: "var(--muted)", fontSize: 10 }} /><YAxis unit=" kW" tick={{ fill: "var(--muted)", fontSize: 10 }} /><Tooltip contentStyle={{ background: "var(--surface-2)", border: "1px solid var(--line)", borderRadius: 10 }} /><Legend wrapperStyle={{ fontSize: 10 }} /><Bar dataKey="solar" name="Solar" stackId="renewable" fill="var(--amber)" /><Bar dataKey="wind" name="Wind" stackId="renewable" fill="var(--blue)" /></BarChart></ResponsiveContainer></div><p className="chart-note">The provider can add hydro, biomass or other sources without changing the operator decision loop.</p></section>
    </div>
    <div className="analytics-grid" style={{ marginTop: 16 }}><section className="card analytics-card analytics-wide"><div className="analytics-heading"><div><div className="label">Operational comparison</div><h2>Baseline versus scheduled demand</h2></div><span className="source">kW · simulated</span></div><div className="analytics-chart compact"><ResponsiveContainer width="100%" height="100%"><BarChart data={data} margin={{ top: 8, right: 10, left: -18, bottom: 4 }}><CartesianGrid stroke="var(--line)" strokeDasharray="3 3" /><XAxis dataKey="time" minTickGap={34} tick={{ fill: "var(--muted)", fontSize: 10 }} /><YAxis unit=" kW" tick={{ fill: "var(--muted)", fontSize: 10 }} /><Tooltip contentStyle={{ background: "var(--surface-2)", border: "1px solid var(--line)", borderRadius: 10 }} /><Legend wrapperStyle={{ fontSize: 11 }} /><Bar dataKey="baseline" name="Baseline" fill="var(--muted)" /><Bar dataKey="scheduled" name="Scheduled" fill="var(--blue)" /></BarChart></ResponsiveContainer></div></section><section className="card analytics-card"><div className="label">Storage state</div><h2>Battery readiness</h2><div className="analytics-chart compact"><ResponsiveContainer width="100%" height="100%"><ComposedChart data={batteryRows} margin={{ top: 8, right: 4, left: -18, bottom: 4 }}><CartesianGrid stroke="var(--line)" strokeDasharray="3 3" /><XAxis dataKey="time" minTickGap={30} tick={{ fill: "var(--muted)", fontSize: 10 }} /><YAxis unit=" kWh" tick={{ fill: "var(--muted)", fontSize: 10 }} /><Tooltip contentStyle={{ background: "var(--surface-2)", border: "1px solid var(--line)", borderRadius: 10 }} /><Line dataKey="soc" name="State of charge" stroke="var(--violet)" strokeWidth={2.5} dot={false} /></ComposedChart></ResponsiveContainer></div><div className="mini-stat"><span>Current</span><strong>{scenario.battery.currentKWh.toFixed(1)} kWh</strong><span>/{scenario.battery.capacityKWh} kWh capacity</span></div></section></div>
    <section className="card recommendations-card"><div className="analytics-heading"><div><div className="label">Ranked operator guidance · read only</div><h2>What should happen next?</h2><p className="muted" style={{ margin: 0 }}>Choose a slot to inspect a transparent score. These are recommendations, never automatic grid commands.</p></div><span className="source">No probability claim</span></div><div className="slot-picker" role="list" aria-label="Select a forecast slot">{[12, 20, 26, 30, 34, 42].map((slot) => <button key={slot} type="button" className={selectedSlot === slot ? "selected" : ""} onClick={() => setSelectedSlot(slot)}>{slotLabel(slot)}<small>{scenario.forecast[slot]?.renewableKW.toFixed(1)} kW RE</small></button>)}</div><div className="selected-slot"><div><strong>{slotLabel(selectedSlot)} IST</strong><span>{selected?.renewableKW.toFixed(1)} kW renewable · {selected ? selectedDemand.toFixed(1) : "–"} kW scheduled demand</span></div><span className={selectedOverload || (selected && selected.renewableKW < selectedDemand) ? "status protect" : "status"}>{selectedOverload ? "Capacity breach" : selected && selected.renewableKW >= selectedDemand ? "Absorb" : "Protect"}</span></div><div className="recommendation-list">{recommendations.length ? recommendations.slice(0, 4).map((item) => <article className="recommendation-item" key={`${item.slot}-${item.action}`}><div className="recommendation-score" aria-label={`score ${item.score} out of 100`}>{item.score}<small>/100</small></div><div className="recommendation-body"><div className="recommendation-title"><strong>{item.title}</strong><span className={`recommendation-state ${item.feasibility}`}>{item.feasibility.replace("_", " ")}</span></div><p>{item.rationale}</p><div className="factor-row">{item.factors.map((factor) => <span key={factor.label}><b>{factor.score}</b> {factor.label}</span>)}</div><div className="recommendation-impact">Expected effect: <strong>{item.impact.powerKW.toFixed(2)} kW</strong> · {item.impact.energyKWh.toFixed(2)} kWh per slot</div><details><summary>Why this score and caveats</summary><ul>{item.factors.map((factor) => <li key={factor.label}>{factor.label}: {factor.detail}</li>)}{item.caveats.map((caveat) => <li key={caveat}>{caveat}</li>)}</ul></details></div></article>) : <p className="notice">No actionable recommendation for this slot. Continue monitoring the next forecast window.</p>}</div></section>
  </div>;
}

function activityPower(activity: Scenario["activities"][number]) { return activity.durationSlots > 0 ? activity.requiredEnergyKWh / (activity.durationSlots * 0.5) : 0; }
