import Link from "next/link";
import type { Scenario } from "@/domain/types";
import { eventReport } from "@/domain/events";
import { summarizeScenario } from "@/domain/summary";

export function OperatorSection({ scenario, section }: { scenario: Scenario; section: "flexibility" | "verification" | "rewards" | "reports" | "settings" }) {
  const summary = summarizeScenario(scenario);
  const offers = scenario.offers;
  const results = Object.values(scenario.results ?? {});
  const verified = scenario.activities.filter((a) => results.some((result) => result.activityId === a.id && result.outcome === "verified"));
  const pendingEvidence = offers.filter((offer) => offer.decision === "accept" && (!scenario.results?.[offer.id] || scenario.results[offer.id].outcome === "pending")).length;
  const verifiedValue = (scenario.rewardLedger ?? []).reduce((sum, entry) => sum + entry.illustrativeRupees, 0);
  const nav = <div className="operator-subnav"><Link href="/operator/overview">← Overview</Link><Link href="/operator/events">Events</Link></div>;
  if (section === "settings") return <main className="shell"><div className="container" style={{ paddingTop: 48 }}>{nav}<div className="eyebrow" style={{ marginTop: 32 }}>Site settings</div><h1>Operating limits that stay visible.</h1><div className="grid metric-grid"><div className="card"><div className="label">Site power limit</div><div className="metric">{scenario.sitePowerLimitKW} kW</div></div><div className="card"><div className="label">Battery capacity</div><div className="metric">{scenario.battery.capacityKWh} kWh</div></div><div className="card"><div className="label">Charge / discharge</div><div className="metric">{scenario.battery.maxChargeKW} / {scenario.battery.maxDischargeKW} kW</div></div><div className="card"><div className="label">Timezone</div><div className="metric" style={{ fontSize: "1.1rem" }}>{scenario.timezone}</div></div></div><p className="footer">These are the current operating limits. Production changes require authorised operator settings.</p></div></main>;
  if (section === "flexibility") return <main className="shell"><div className="container" style={{ paddingTop: 48 }}>{nav}<div className="eyebrow" style={{ marginTop: 32 }}>Flexibility · scheduled programme</div><h1>Accepted capacity you can defend.</h1><div className="grid metric-grid"><div className="card"><div className="label">Offers</div><div className="metric amber">{offers.length}</div></div><div className="card"><div className="label">Accepted capacity</div><div className="metric blue">{summary.acceptedKW.toFixed(1)} kW</div></div><div className="card"><div className="label">Verified capacity</div><div className="metric violet">{summary.verifiedKW.toFixed(1)} kW</div></div><div className="card"><div className="label">Pending evidence</div><div className="metric">{pendingEvidence}</div></div></div><div className="card" style={{ marginTop: 16 }}><h2>Participant commitments</h2>{offers.map((offer) => <p key={offer.id}><strong>{scenario.activities.find((a) => a.id === offer.activityId)?.name ?? "Activity"}</strong> · {offer.decision} · {offer.proposedEnd - offer.proposedStart} slots · ₹{offer.rewardEstimate.toFixed(2)} reward estimate</p>)}</div></div></main>;
  if (section === "verification") return <main className="shell"><div className="container" style={{ paddingTop: 48 }}>{nav}<div className="eyebrow" style={{ marginTop: 32 }}>Verification · evidence queue</div><h1>Evidence before reward.</h1><div className="grid metric-grid"><div className="card"><div className="label">Accepted</div><div className="metric blue">{offers.filter((o) => o.decision === "accept").length}</div></div><div className="card"><div className="label">Readings received</div><div className="metric amber">{scenario.readings.length}</div></div><div className="card"><div className="label">Verified activities</div><div className="metric violet">{verified.length}</div></div><div className="card"><div className="label">Pending evidence</div><div className="metric">{pendingEvidence}</div></div></div><div className="card" style={{ marginTop: 16 }}><h2>Next safe action</h2><p className="muted">{pendingEvidence ? "Review the reading queue to process submitted evidence. Missing evidence remains pending." : "Review received evidence and release only verified rewards."}</p><Link className="primary-button" href="/operator/evidence">Review readings</Link></div></div></main>;
  if (section === "rewards") { return <main className="shell"><div className="container" style={{ paddingTop: 48 }}>{nav}<div className="eyebrow" style={{ marginTop: 32 }}>Rewards · programme ledger</div><h1>Programme budget with evidence.</h1><div className="grid metric-grid"><div className="card"><div className="label">Event budget</div><div className="metric">₹{scenario.events[0]?.budget ?? 0}</div></div><div className="card"><div className="label">Estimated accepted</div><div className="metric amber">₹{offers.filter((o) => o.decision === "accept").reduce((n, o) => n + o.rewardEstimate, 0).toFixed(2)}</div></div><div className="card"><div className="label">Verified ledger value</div><div className="metric violet">₹{verifiedValue.toFixed(2)}</div></div><div className="card"><div className="label">Payment status</div><div className="metric" style={{ fontSize: "1.1rem" }}>Illustrative</div></div></div><p className="footer">No real payment is made. Rewards are eligible only after scenario or authorised device evidence is verified.</p></div></main>; }
  return <main className="shell"><div className="container" style={{ paddingTop: 48 }}>{nav}<div className="eyebrow" style={{ marginTop: 32 }}>Reports · event funnel</div><h1>From recommendation to verified response.</h1>{scenario.events.map((event) => { const report = eventReport(scenario, event.id); return <div className="card" key={event.id} style={{ marginTop: 16 }}><div style={{ display: "flex", justifyContent: "space-between", gap: 12 }}><div><h2>{event.name}</h2><p className="muted">{event.objective === "absorb" ? "Renewable surplus absorption" : "Peak support"} · {event.status}</p></div><span className="source">Scenario estimate</span></div><div className="grid metric-grid" style={{ marginTop: 16 }}><div><div className="label">Recommended</div><div className="metric amber">{report.funnel.recommended}</div></div><div><div className="label">Accepted</div><div className="metric blue">{report.funnel.accepted}</div></div><div><div className="label">Completed</div><div className="metric">{report.funnel.completed}</div></div><div><div className="label">Verified</div><div className="metric violet">{report.funnel.verified}</div></div></div><a className="text-link" href={`/api/events/${event.id}/report?format=csv`}>Download CSV report →</a></div>; })}<p className="footer">Reports use the same scenario event records as the operator overview. Values are estimates until approved utility data is connected.</p></div></main>;
}
